"""align_schema_with_docs

Revision ID: a954badedcfe
Revises: ffa9e5fe9c90
Create Date: 2025-12-22 21:37:31.294585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a954badedcfe"
down_revision: Union[str, Sequence[str], None] = "ffa9e5fe9c90"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "characters",
        "roles",
        existing_type=postgresql.ARRAY(
            postgresql.ENUM(
                "Tank", "Healer", "DPS", name="characterroleenum", create_type=False
            )
        ),
        type_=postgresql.ARRAY(sa.String()),
        existing_nullable=False,
    )
    op.alter_column(
        "factions",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "item_sets",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("nextval('item_sets_id_seq'::regclass)"),
    )
    op.alter_column(
        "item_sets",
        "items_in_set_ids",
        existing_type=postgresql.ARRAY(sa.INTEGER()),
        type_=postgresql.ARRAY(sa.BigInteger()),
        existing_nullable=False,
    )
    op.alter_column(
        "items",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "items",
        "set_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "npcs",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("nextval('npcs_id_seq'::regclass)"),
    )
    op.alter_column(
        "npcs",
        "faction_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    op.alter_column(
        "quests",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "quests",
        "quest_giver_npc_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "quests",
        "quest_turnin_npc_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "spells",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.add_column("talents", sa.Column("column", sa.Integer(), nullable=True))
    op.drop_column("talents", "talent_column")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "talents",
        sa.Column("talent_column", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_column("talents", "column")
    op.alter_column(
        "spells",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "quests",
        "quest_turnin_npc_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "quests",
        "quest_giver_npc_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "quests",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "npcs",
        "faction_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "npcs",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("nextval('npcs_id_seq'::regclass)"),
    )
    op.alter_column(
        "items",
        "set_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "items",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "item_sets",
        "items_in_set_ids",
        existing_type=postgresql.ARRAY(sa.BigInteger()),
        type_=postgresql.ARRAY(sa.INTEGER()),
        existing_nullable=False,
    )
    op.alter_column(
        "item_sets",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("nextval('item_sets_id_seq'::regclass)"),
    )
    op.alter_column(
        "factions",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "characters",
        "roles",
        existing_type=postgresql.ARRAY(sa.String()),
        type_=postgresql.ARRAY(
            postgresql.ENUM(
                "Tank", "Healer", "DPS", name="characterroleenum", create_type=False
            )
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
