"""initial_clean_schema

Revision ID: a225a52069c3
Revises:
Create Date: 2026-01-04 18:59:10.324811

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a225a52069c3"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "characters",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("discord_user_id", sa.BigInteger(), nullable=False),
        sa.Column("discord_username", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column(
            "race",
            sa.Enum(
                "Human",
                "Dwarf",
                "NightElf",
                "Gnome",
                "Orc",
                "Troll",
                "Tauren",
                "Undead",
                "Goblin",
                "HighElf",
                "Other",
                name="characterraceenum",
            ),
            nullable=False,
        ),
        sa.Column(
            "class",
            sa.Enum(
                "Warrior",
                "Paladin",
                "Hunter",
                "Rogue",
                "Priest",
                "Shaman",
                "Mage",
                "Warlock",
                "Druid",
                name="characterclassenum",
            ),
            nullable=False,
        ),
        sa.Column("roles", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("professions", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("backstory", sa.Text(), nullable=False),
        sa.Column("personality", sa.Text(), nullable=True),
        sa.Column("quotes", sa.Text(), nullable=True),
        sa.Column("portrait_url", sa.Text(), nullable=True),
        sa.Column("trait_1", sa.String(length=128), nullable=False),
        sa.Column("trait_2", sa.String(length=128), nullable=False),
        sa.Column("trait_3", sa.String(length=128), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "REGISTERED",
                "REJECTED",
                "DECEASED",
                "BURIED",
                name="characterstatusenum",
            ),
            nullable=False,
        ),
        sa.Column("is_confirmed", sa.Boolean(), nullable=False),
        sa.Column("request_sdxl", sa.Boolean(), nullable=False),
        sa.Column("recruitment_msg_id", sa.BigInteger(), nullable=True),
        sa.Column("forum_post_id", sa.BigInteger(), nullable=True),
        sa.Column("reviewed_by_user_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "embed_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("death_cause", sa.String(length=256), nullable=True),
        sa.Column("death_story", sa.Text(), nullable=True),
        sa.Column(
            "talents_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("forum_post_id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "factions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("turtle_db_url", sa.Text(), nullable=True),
        sa.Column(
            "alignment",
            sa.Enum(
                "Alliance", "Horde", "Neutral", "Hostile", name="factionalignmentenum"
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("crest_url", sa.Text(), nullable=True),
        sa.Column("primary_color_hex", sa.String(length=7), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "images",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("img_origin_link", sa.Text(), nullable=False),
        sa.Column("img_graphics_vault_link", sa.Text(), nullable=False),
        sa.Column("original_filename", sa.String(length=256), nullable=False),
        sa.Column("uploaded_by_user_id", sa.BigInteger(), nullable=True),
        sa.Column("source_system", sa.String(length=64), nullable=False),
        sa.Column("ownership_context", sa.String(length=64), nullable=False),
        sa.Column("usage_context", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=True),
        sa.Column("entity_id", sa.BigInteger(), nullable=True),
        sa.Column("category_tags", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("provenance_notes", sa.Text(), nullable=True),
        sa.Column("permissions_level", sa.String(length=32), nullable=False),
        sa.Column("is_animated", sa.Boolean(), nullable=False),
        sa.Column("hash_md5", sa.String(length=32), nullable=True),
        sa.Column(
            "upload_timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("last_accessed_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hash_md5"),
        sa.UniqueConstraint("img_graphics_vault_link"),
    )
    op.create_table(
        "item_sets",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("turtle_db_url", sa.Text(), nullable=False),
        sa.Column("icon_url", sa.Text(), nullable=True),
        sa.Column("required_level", sa.Integer(), nullable=True),
        sa.Column(
            "set_bonuses_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "items_in_set_ids", postgresql.ARRAY(sa.BigInteger()), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "talent_trees",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column(
            "class",
            sa.Enum(
                "Warrior",
                "Paladin",
                "Hunter",
                "Rogue",
                "Priest",
                "Shaman",
                "Mage",
                "Warlock",
                "Druid",
                name="characterclassenum",
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("background_image_url", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "character_talents",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("talent_tree_id", sa.String(length=255), nullable=False),
        sa.Column("talent_id", sa.String(length=255), nullable=False),
        sa.Column("points_spent", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.CheckConstraint("points_spent >= 0", name="points_spent_positive"),
        sa.ForeignKeyConstraint(
            ["character_id"], ["characters.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("character_id", "talent_id", name="uq_character_talent"),
    )
    op.create_table(
        "graveyard",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column(
            "death_timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("cause_of_death", sa.Text(), nullable=True),
        sa.Column("eulogy", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["character_id"], ["characters.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "items",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("turtle_db_url", sa.Text(), nullable=False),
        sa.Column("icon_url", sa.Text(), nullable=False),
        sa.Column(
            "quality",
            sa.Enum(
                "Poor",
                "Common",
                "Uncommon",
                "Rare",
                "Epic",
                "Legendary",
                name="itemqualityenum",
            ),
            nullable=False,
        ),
        sa.Column("item_type", sa.String(length=64), nullable=False),
        sa.Column("item_subtype", sa.String(length=64), nullable=True),
        sa.Column("inventory_slot", sa.String(length=64), nullable=True),
        sa.Column("item_level", sa.Integer(), nullable=True),
        sa.Column("required_level", sa.Integer(), nullable=True),
        sa.Column("binding", sa.String(length=32), nullable=True),
        sa.Column("armor", sa.Integer(), nullable=True),
        sa.Column("min_damage", sa.Integer(), nullable=True),
        sa.Column("max_damage", sa.Integer(), nullable=True),
        sa.Column("speed", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("durability", sa.Integer(), nullable=True),
        sa.Column("sell_price_copper", sa.Integer(), nullable=True),
        sa.Column("buy_price_copper", sa.Integer(), nullable=True),
        sa.Column("stats_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("use_effect_description", sa.Text(), nullable=True),
        sa.Column("equip_effect_description", sa.Text(), nullable=True),
        sa.Column("set_id", sa.BigInteger(), nullable=True),
        sa.Column("source_type", sa.String(length=64), nullable=True),
        sa.Column(
            "source_details_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.CheckConstraint(
            "required_level >= 1 AND required_level <= 60",
            name="item_required_level_range",
        ),
        sa.ForeignKeyConstraint(
            ["set_id"],
            ["item_sets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "npcs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("turtle_db_url", sa.Text(), nullable=False),
        sa.Column(
            "creature_type",
            sa.Enum(
                "Beast",
                "Demon",
                "Dragonkin",
                "Elemental",
                "Giant",
                "Humanoid",
                "Mechanical",
                "Undead",
                "Critter",
                "Totem",
                "Other",
                name="creaturetypeenum",
            ),
            nullable=False,
        ),
        sa.Column("race", sa.String(length=64), nullable=True),
        sa.Column("faction_id", sa.BigInteger(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=True),
        sa.Column("classification", sa.String(length=64), nullable=True),
        sa.Column("zone", sa.String(length=128), nullable=True),
        sa.Column(
            "coordinates_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("role", sa.String(length=64), nullable=True),
        sa.Column("model_url", sa.Text(), nullable=True),
        sa.Column(
            "abilities_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("is_vendor", sa.Boolean(), nullable=False),
        sa.Column("is_quest_giver", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.CheckConstraint("level >= 1 AND level <= 63", name="npc_level_range"),
        sa.ForeignKeyConstraint(
            ["faction_id"],
            ["factions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "talents",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("tree_id", sa.String(length=64), nullable=False),
        sa.Column("tier", sa.Integer(), nullable=False),
        sa.Column("column", sa.Integer(), nullable=True),
        sa.Column("max_rank", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("icon_url", sa.Text(), nullable=False),
        sa.Column("prerequisite_id", sa.String(length=128), nullable=True),
        sa.Column("points_req", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.CheckConstraint(
            '"column" >= 1 AND "column" <= 4', name="talent_column_range"
        ),
        sa.CheckConstraint("max_rank >= 1", name="talent_max_rank_positive"),
        sa.CheckConstraint("tier >= 1 AND tier <= 7", name="talent_tier_range"),
        sa.ForeignKeyConstraint(
            ["prerequisite_id"],
            ["talents.id"],
        ),
        sa.ForeignKeyConstraint(["tree_id"], ["talent_trees.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "guild_bank_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("item_id", sa.BigInteger(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("location", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.CheckConstraint("count >= 0", name="bank_item_count_positive"),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "guild_bank_transactions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("item_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "transaction_type",
            sa.Enum("DEPOSIT", "WITHDRAWAL", name="banktransactiontypeenum"),
            nullable=False,
        ),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint("quantity > 0", name="transaction_quantity_positive"),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "quests",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("turtle_db_url", sa.Text(), nullable=False),
        sa.Column(
            "quest_type",
            sa.Enum(
                "Normal",
                "Daily",
                "Dungeon",
                "Raid",
                "Profession",
                "ClassQuest",
                "Legendary",
                name="questtypeenum",
            ),
            nullable=False,
        ),
        sa.Column("required_level", sa.Integer(), nullable=False),
        sa.Column("zone", sa.String(length=128), nullable=False),
        sa.Column("quest_giver_npc_id", sa.BigInteger(), nullable=True),
        sa.Column("quest_turnin_npc_id", sa.BigInteger(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "objectives_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("completion_text", sa.Text(), nullable=True),
        sa.Column("xp_reward", sa.Integer(), nullable=False),
        sa.Column("gold_reward_copper", sa.Integer(), nullable=False),
        sa.Column(
            "item_rewards_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "reputation_rewards_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.CheckConstraint(
            "required_level >= 1 AND required_level <= 60",
            name="quest_required_level_range",
        ),
        sa.ForeignKeyConstraint(
            ["quest_giver_npc_id"],
            ["npcs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["quest_turnin_npc_id"],
            ["npcs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "spells",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("turtle_db_url", sa.Text(), nullable=False),
        sa.Column("icon_url", sa.Text(), nullable=False),
        sa.Column(
            "spell_school",
            sa.Enum(
                "Physical",
                "Arcane",
                "Fire",
                "Frost",
                "Nature",
                "Shadow",
                "Holy",
                name="spellschoolenum",
            ),
            nullable=False,
        ),
        sa.Column("spell_type", sa.String(length=64), nullable=True),
        sa.Column("rank", sa.String(length=32), nullable=True),
        sa.Column("cast_time", sa.String(length=64), nullable=False),
        sa.Column("cooldown", sa.String(length=64), nullable=True),
        sa.Column("mana_cost", sa.String(length=64), nullable=True),
        sa.Column("range", sa.String(length=64), nullable=True),
        sa.Column("duration", sa.String(length=64), nullable=True),
        sa.Column("target_type", sa.String(length=64), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "effect_details_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("talent_id", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["talent_id"],
            ["talents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("spells")
    op.drop_table("quests")
    op.drop_table("guild_bank_transactions")
    op.drop_table("guild_bank_items")
    op.drop_table("talents")
    op.drop_table("npcs")
    op.drop_table("items")
    op.drop_table("graveyard")
    op.drop_table("character_talents")
    op.drop_table("talent_trees")
    op.drop_table("item_sets")
    op.drop_table("images")
    op.drop_table("factions")
    op.drop_table("characters")
    # ### end Alembic commands ###
