# domain/talent_data.py
# This is a simplified representation of talent data for WoW Classic+.
# The actual talent data would be much more complex and would depend on the specific
# implementation of the Classic+ server.
TALENT_DATA = {
    "Warrior": {
        "Arms": {
            "Improved Heroic Strike": {"level": 10, "max_rank": 3},
            "Tactical Mastery": {"level": 10, "max_rank": 5},
            "Improved Rend": {"level": 10, "max_rank": 2},
            "Improved Charge": {"level": 10, "max_rank": 2},
            "Master Strike": {"level": 10, "max_rank": 1},
            "Improved Overpower": {"level": 10, "max_rank": 2},
            "Deep Wounds": {"level": 10, "max_rank": 3},
            "Two-Handed Weapon Specialization": {"level": 10, "max_rank": 3},
            "Impale": {"level": 10, "max_rank": 2},
            "Master of Arms": {"level": 10, "max_rank": 5},
            "Sweeping Strikes": {"level": 10, "max_rank": 1},
            "Precision Cut": {"level": 10, "max_rank": 3},
            "Improved Disciplines": {"level": 10, "max_rank": 3},
            "Improved Slam": {"level": 10, "max_rank": 2},
            "Mortal Strike": {"level": 10, "max_rank": 1},
            "Boundless Anger": {"level": 10, "max_rank": 3},
            "Booming Voice": {"level": 10, "max_rank": 5},
            "Piercing Howl": {"level": 10, "max_rank": 1},
            "Improved Execute": {"level": 10, "max_rank": 2},
        },
        "Fury": {
            "Cruelty": {"level": 10, "max_rank": 5},
            "Dual Wield Specialization": {"level": 10, "max_rank": 5},
            "Unbridled Wrath": {"level": 10, "max_rank": 5},
            "Improved Shouts": {"level": 10, "max_rank": 5},
            "Blood Craze": {"level": 10, "max_rank": 3},
            "Battlefield Mobility": {"level": 10, "max_rank": 2},
            "Enrage": {"level": 10, "max_rank": 5},
            "Improved Pummel": {"level": 10, "max_rank": 2},
            "Improved Whirlwind": {"level": 10, "max_rank": 3},
            "Death Wish": {"level": 10, "max_rank": 1},
            "Improved Berserker Rage": {"level": 10, "max_rank": 2},
            "Flurry": {"level": 10, "max_rank": 5},
            "Blood Drinker": {"level": 10, "max_rank": 3},
            "Bloodthirst": {"level": 10, "max_rank": 1},
            "Improved Bloodrage": {"level": 10, "max_rank": 2},
        },
        "Protection": {
            "Deflection": {"level": 10, "max_rank": 5},
            "Improved Thunder Clap": {"level": 10, "max_rank": 3},
            "Shield Specialization": {"level": 10, "max_rank": 5},
            "Anticipation": {"level": 10, "max_rank": 3},
            "Iron Will": {"level": 10, "max_rank": 5},
            "Toughness": {"level": 10, "max_rank": 5},
            "Last Stand": {"level": 10, "max_rank": 1},
            "Improved Intervene": {"level": 10, "max_rank": 2},
            "Improved Taunt": {"level": 10, "max_rank": 2},
            "Improved Revenge": {"level": 10, "max_rank": 3},
            "Gag Order": {"level": 10, "max_rank": 2},
            "Improved Disarm": {"level": 10, "max_rank": 2},
            "Defiance": {"level": 10, "max_rank": 5},
            "One-Handed Weapon Specialization": {"level": 10, "max_rank": 5},
            "Shield Slam": {"level": 10, "max_rank": 1},
            "Improved Shield Slam": {"level": 10, "max_rank": 2},
            "Reprisal": {"level": 10, "max_rank": 2},
            "Improved Shield Wall": {"level": 10, "max_rank": 2},
            "Defensive Tactics": {"level": 10, "max_rank": 3},
            "Concussion Blow": {"level": 10, "max_rank": 1},
        }
    },
    "Paladin": {
        "Holy": {
            "Divine Intellect": {"level": 10, "max_rank": 5},
            "Holy Judgement": {"level": 10, "max_rank": 3},
            "Spiritual Focus": {"level": 10, "max_rank": 2},
            "Improved Seal of Righteousness": {"level": 10, "max_rank": 5},
            "Healing Light": {"level": 10, "max_rank": 3},
            "Sanctity Aura": {"level": 10, "max_rank": 1},
            "Illumination": {"level": 10, "max_rank": 5},
            "Divine Favor": {"level": 10, "max_rank": 5},
            "Holy Shock": {"level": 10, "max_rank": 1},
            "Holy Power": {"level": 10, "max_rank": 3},
            "Blessed Strikes": {"level": 10, "max_rank": 5},
            "Daybreak": {"level": 10, "max_rank": 1},
            "Improved Lay on Hands": {"level": 10, "max_rank": 2},
        },
        "Protection": {
            "Improved Devotion Aura": {"level": 10, "max_rank": 5},
            "Redoubt": {"level": 10, "max_rank": 5},
            "Precision": {"level": 10, "max_rank": 3},
            "Guardian's Favor": {"level": 10, "max_rank": 2},
            "Toughness": {"level": 10, "max_rank": 5},
            "Improved Righteous Fury": {"level": 10, "max_rank": 3},
            "Blessing of Sanctuary": {"level": 10, "max_rank": 1},
            "Shield Specialization": {"level": 10, "max_rank": 3},
            "Anticipation": {"level": 10, "max_rank": 3},
            "Improved Hand of Reckoning": {"level": 10, "max_rank": 2},
            "Improved Hammer of Justice": {"level": 10, "max_rank": 3},
            "Righteous Defense": {"level": 10, "max_rank": 3},
            "Holy Shield": {"level": 10, "max_rank": 1},
            "Reckoning": {"level": 10, "max_rank": 5},
            "Righteous Strikes": {"level": 10, "max_rank": 5},
            "Bulwark of the Righteous": {"level": 10, "max_rank": 1},
        },
        "Retribution": {
            "Improved Blessings": {"level": 10, "max_rank": 5},
            "Benediction": {"level": 10, "max_rank": 5},
            "Improved Judgement": {"level": 10, "max_rank": 2},
            "Improved Seal of the Crusader": {"level": 10, "max_rank": 3},
            "Deflection": {"level": 10, "max_rank": 5},
            "Improved Retribution Aura": {"level": 10, "max_rank": 2},
            "Conviction": {"level": 10, "max_rank": 5},
            "Blessing of Kings": {"level": 10, "max_rank": 1},
            "Pursuit of Justice": {"level": 10, "max_rank": 2},
            "Two-Handed Weapon Specialization": {"level": 10, "max_rank": 3},
            "Vindication": {"level": 10, "max_rank": 3},
            "Eye for an Eye": {"level": 10, "max_rank": 2},
            "Vengeance": {"level": 10, "max_rank": 5},
            "Seal of Command": {"level": 10, "max_rank": 1},
            "Vengeful Strikes": {"level": 10, "max_rank": 5},
            "Repentance": {"level": 10, "max_rank": 1},
            "Divine Strength": {"level": 10, "max_rank": 5},
        }
    },
    "Hunter": {
        "Beast Mastery": {
            "Swift Aspects": {"level": 10, "max_rank": 5},
            "Endurance Training": {"level": 10, "max_rank": 5},
            "Improved Eyes of the Beast": {"level": 10, "max_rank": 2},
            "Improved Primal Aspects": {"level": 10, "max_rank": 3},
            "Thick Hide": {"level": 10, "max_rank": 3},
            "Improved Revive Pet": {"level": 10, "max_rank": 2},
            "Pathfinding": {"level": 10, "max_rank": 2},
            "Coordinated Assault": {"level": 10, "max_rank": 1},
            "Unleashed Fury": {"level": 10, "max_rank": 5},
            "Bestial Discipline": {"level": 10, "max_rank": 2},
            "Improved Mend Pet": {"level": 10, "max_rank": 2},
            "Ferocity": {"level": 10, "max_rank": 5},
            "Intimidation": {"level": 10, "max_rank": 1},
            "Kill Command": {"level": 10, "max_rank": 1},
            "Bestial Precision": {"level": 10, "max_rank": 2},
            "Spirit Bond": {"level": 10, "max_rank": 2},
            "Frenzy": {"level": 10, "max_rank": 5},
            "Baited Shot": {"level": 10, "max_rank": 1},
        },
        "Marksmanship": {
            "Improved Concussive Shot": {"level": 10, "max_rank": 5},
            "Efficiency": {"level": 10, "max_rank": 5},
            "Improved Stings": {"level": 10, "max_rank": 5},
            "Lethal Shots": {"level": 10, "max_rank": 5},
            "Hawk Eye": {"level": 10, "max_rank": 2},
            "Improved Scorpid Sting": {"level": 10, "max_rank": 2},
            "Steady Shot": {"level": 10, "max_rank": 1},
            "Improved Hunter's Mark": {"level": 10, "max_rank": 3},
            "Swiftshot": {"level": 10, "max_rank": 3},
            "Mortal Shots": {"level": 10, "max_rank": 5},
            "Scatter Shot": {"level": 10, "max_rank": 1},
            "Barrage": {"level": 10, "max_rank": 3},
            "Piercing Shots": {"level": 10, "max_rank": 2},
            "Improved Steady Shot": {"level": 10, "max_rank": 2},
            "Endless Quiver": {"level": 10, "max_rank": 2},
            "Ranged Weapon Specialization": {"level": 10, "max_rank": 5},
            "Trueshot Aura": {"level": 10, "max_rank": 1},
        },
        "Survival": {
            "Improved Slaying": {"level": 10, "max_rank": 3},
            "Resourcefulness": {"level": 10, "max_rank": 5},
            "Swift Reflexes": {"level": 10, "max_rank": 2},
            "Entrapment": {"level": 10, "max_rank": 3},
            "Savage Strikes": {"level": 10, "max_rank": 2},
            "Improved Wing Clip": {"level": 10, "max_rank": 3},
            "Planning Ahead": {"level": 10, "max_rank": 2},
            "Survivalist": {"level": 10, "max_rank": 5},
            "Carve": {"level": 10, "max_rank": 1},
            "Deterrence": {"level": 10, "max_rank": 1},
            "Stinging Nettle": {"level": 10, "max_rank": 2},
            "Surefooted": {"level": 10, "max_rank": 3},
            "Improved Feign Death": {"level": 10, "max_rank": 2},
            "Killer Instinct": {"level": 10, "max_rank": 3},
            "Trap Mastery": {"level": 10, "max_rank": 3},
            "Lacerate": {"level": 10, "max_rank": 1},
            "Vicious Strikes": {"level": 10, "max_rank": 2},
            "Lightning Reflexes": {"level": 10, "max_rank": 5},
            "Untamed Trapper": {"level": 10, "max_rank": 1},
        }
    },
    "Rogue": {
        "Assassination": {
            "Improved Eviscerate": {"level": 10, "max_rank": 3},
            "Remorseless Attacks": {"level": 10, "max_rank": 2},
            "Malice": {"level": 10, "max_rank": 5},
            "Ruthlessness": {"level": 10, "max_rank": 3},
            "Murder": {"level": 10, "max_rank": 2},
            "Improved Blade Tactics": {"level": 10, "max_rank": 3},
            "Relentless Strikes": {"level": 10, "max_rank": 1},
            "Throwing Weapon Specialization": {"level": 10, "max_rank": 2},
            "Lethality": {"level": 10, "max_rank": 5},
            "Taste for Blood": {"level": 10, "max_rank": 3},
            "Vile Poisons": {"level": 10, "max_rank": 3},
            "Improved Poisons": {"level": 10, "max_rank": 3},
            "Efficient Poisons": {"level": 10, "max_rank": 3},
            "Envenom": {"level": 10, "max_rank": 1},
            "Cold Blood": {"level": 10, "max_rank": 1},
            "Vigor": {"level": 10, "max_rank": 2},
            "Seal Fate": {"level": 10, "max_rank": 5},
            "Noxious Assault": {"level": 10, "max_rank": 1},
        },
        "Combat": {
            "Opportunity": {"level": 10, "max_rank": 5},
            "Lightning Reflexes": {"level": 10, "max_rank": 5},
            "Deflection": {"level": 10, "max_rank": 5},
            "Improved Backstab": {"level": 10, "max_rank": 3},
            "Precision": {"level": 10, "max_rank": 5},
            "Riposte": {"level": 10, "max_rank": 1},
            "Improved Sprint": {"level": 10, "max_rank": 2},
            "Setup": {"level": 10, "max_rank": 3},
            "Improved Kick": {"level": 10, "max_rank": 2},
            "Concussive Blows": {"level": 10, "max_rank": 5},
            "Dual Wield Specialization": {"level": 10, "max_rank": 5},
            "Close Quarters Combat": {"level": 10, "max_rank": 2},
            "Surprise Attack": {"level": 10, "max_rank": 1},
            "Hack and Slash": {"level": 10, "max_rank": 2},
            "Weapon Expertise": {"level": 10, "max_rank": 2},
            "Blade Rush": {"level": 10, "max_rank": 2},
            "Aggression": {"level": 10, "max_rank": 3},
            "Adrenaline Rush": {"level": 10, "max_rank": 1},
        },
        "Subtlety": {
            "Camouflage": {"level": 10, "max_rank": 5},
            "Improved Expose Armor": {"level": 10, "max_rank": 2},
            "Improved Gouge": {"level": 10, "max_rank": 3},
            "Improved Ambush": {"level": 10, "max_rank": 3},
            "Elusiveness": {"level": 10, "max_rank": 2},
            "Serrated Blades": {"level": 10, "max_rank": 3},
            "Initiative": {"level": 10, "max_rank": 3},
            "Improved Ghostly Strike": {"level": 10, "max_rank": 3},
            "Smoke Bomb": {"level": 10, "max_rank": 1},
            "Hemorrhage": {"level": 10, "max_rank": 1},
            "Cloaked in Shadows": {"level": 10, "max_rank": 2},
            "Blackjack": {"level": 10, "max_rank": 2},
            "Blinding Haze": {"level": 10, "max_rank": 3},
            "Dirty Deeds": {"level": 10, "max_rank": 2},
            "Preparation": {"level": 10, "max_rank": 1},
            "Shadow of Death": {"level": 10, "max_rank": 1},
            "Bloody Mess": {"level": 10, "max_rank": 2},
            "Honor Among Thieves": {"level": 10, "max_rank": 2},
            "Tricks of the Trade": {"level": 10, "max_rank": 5},
            "Mark for Death": {"level": 10, "max_rank": 1},
        }
    },
    "Priest": {
        "Discipline": {
            "Wand Specialization": {"level": 10, "max_rank": 2},
            "Piercing Light": {"level": 10, "max_rank": 3},
            "Mental Agility": {"level": 10, "max_rank": 5},
            "Silent Resolve": {"level": 10, "max_rank": 5},
            "Unbreakable Will": {"level": 10, "max_rank": 5},
            "Blessed Concentration": {"level": 10, "max_rank": 2},
            "Improved Power Word: Fortitude": {"level": 10, "max_rank": 2},
            "Improved Inner Fire": {"level": 10, "max_rank": 2},
            "Inner Focus": {"level": 10, "max_rank": 1},
            "Improved Power Word: Shield": {"level": 10, "max_rank": 3},
            "Meditation": {"level": 10, "max_rank": 3},
            "Searing Light": {"level": 10, "max_rank": 3},
            "Purifying Flames": {"level": 10, "max_rank": 2},
            "Mental Strength": {"level": 10, "max_rank": 3},
            "Enlighten": {"level": 10, "max_rank": 1},
            "Resurgent Shield": {"level": 10, "max_rank": 1},
            "Force of Will": {"level": 10, "max_rank": 5},
            "Chastise": {"level": 10, "max_rank": 1},
        },
        "Holy": {
            "Improved Renew": {"level": 10, "max_rank": 3},
            "Holy Focus": {"level": 10, "max_rank": 2},
            "Divinity": {"level": 10, "max_rank": 5},
            "Divine Fury": {"level": 10, "max_rank": 5},
            "Spell Warding": {"level": 10, "max_rank": 3},
            "Holy Reach": {"level": 10, "max_rank": 2},
            "Blessed Recovery": {"level": 10, "max_rank": 3},
            "Inspiration": {"level": 10, "max_rank": 3},
            "Holy Nova": {"level": 10, "max_rank": 1},
            "Swift Recovery": {"level": 10, "max_rank": 2},
            "Improved Healing": {"level": 10, "max_rank": 3},
            "Spiritual Guidance": {"level": 10, "max_rank": 5},
            "Spirit of Redemption": {"level": 10, "max_rank": 1},
            "Reservoir of Light": {"level": 10, "max_rank": 3},
            "Spiritual Healing": {"level": 10, "max_rank": 5},
            "Proclaim Champion": {"level": 10, "max_rank": 1},
        },
        "Shadow": {
            "Spirit Tap": {"level": 10, "max_rank": 5},
            "Blackout": {"level": 10, "max_rank": 5},
            "Shadow Affinity": {"level": 10, "max_rank": 3},
            "Improved Shadow Word: Pain": {"level": 10, "max_rank": 2},
            "Shadow Focus": {"level": 10, "max_rank": 5},
            "Improved Psychic Scream": {"level": 10, "max_rank": 2},
            "Improved Mind Blast": {"level": 10, "max_rank": 5},
            "Mind Flay": {"level": 10, "max_rank": 1},
            "Improved Mana Burn": {"level": 10, "max_rank": 2},
            "Improved Fade": {"level": 10, "max_rank": 2},
            "Shadow Reach": {"level": 10, "max_rank": 3},
            "Shadow Weaving": {"level": 10, "max_rank": 5},
            "Silence": {"level": 10, "max_rank": 1},
            "Vampiric Embrace": {"level": 10, "max_rank": 1},
            "Vampiric Touch": {"level": 10, "max_rank": 2},
            "Darkness": {"level": 10, "max_rank": 5},
            "Shadowform": {"level": 10, "max_rank": 1},
        }
    },
    "Shaman": {
        "Elemental": {
            "Convection": {"level": 10, "max_rank": 5},
            "Concussion": {"level": 10, "max_rank": 5},
            "Earth's Grasp": {"level": 10, "max_rank": 2},
            "Elemental Warding": {"level": 10, "max_rank": 3},
            "Elemental Devastation": {"level": 10, "max_rank": 3},
            "Elemental Focus": {"level": 10, "max_rank": 1},
            "Reverberation": {"level": 10, "max_rank": 3},
            "Call of Thunder": {"level": 10, "max_rank": 5},
            "Improved Molten Blast": {"level": 10, "max_rank": 2},
            "Improved Fire Totems": {"level": 10, "max_rank": 2},
            "Eye of the Storm": {"level": 10, "max_rank": 3},
            "Call of Flame": {"level": 10, "max_rank": 3},
            "Storm Reach": {"level": 10, "max_rank": 2},
            "Elemental Mastery": {"level": 10, "max_rank": 1},
            "Elemental Fury": {"level": 10, "max_rank": 2},
            "Lightning Mastery": {"level": 10, "max_rank": 5},
            "Earthquake": {"level": 10, "max_rank": 1},
        },
        "Enhancement": {
            "Ancestral Knowledge": {"level": 10, "max_rank": 5},
            "Shield Specialization": {"level": 10, "max_rank": 5},
            "Totemic Alignment": {"level": 10, "max_rank": 2},
            "Thundering Strikes": {"level": 10, "max_rank": 5},
            "Stable Shields": {"level": 10, "max_rank": 3},
            "Improved Ghost Wolf": {"level": 10, "max_rank": 2},
            "Calming Winds": {"level": 10, "max_rank": 3},
            "Lightning Strike": {"level": 10, "max_rank": 1},
            "Ancestral Guardian": {"level": 10, "max_rank": 3},
            "Flurry": {"level": 10, "max_rank": 5},
            "Spirit Armor": {"level": 10, "max_rank": 2},
            "Enhancing Totems": {"level": 10, "max_rank": 2},
            "Elemental Weapons": {"level": 10, "max_rank": 3},
            "Stormstrike": {"level": 10, "max_rank": 1},
            "Element's Grace": {"level": 10, "max_rank": 5},
            "Bloodlust": {"level": 10, "max_rank": 1},
        },
        "Restoration": {
            "Improved Healing Wave": {"level": 10, "max_rank": 5},
            "Tidal Focus": {"level": 10, "max_rank": 5},
            "Improved Reincarnation": {"level": 10, "max_rank": 2},
            "Ancestral Healing": {"level": 10, "max_rank": 3},
            "Tidal Mastery": {"level": 10, "max_rank": 5},
            "Healing Way": {"level": 10, "max_rank": 3},
            "Healing Focus": {"level": 10, "max_rank": 2},
            "Totemic Mastery": {"level": 10, "max_rank": 1},
            "Nature's Grace": {"level": 10, "max_rank": 3},
            "Restorative Totems": {"level": 10, "max_rank": 5},
            "Improved Water Shield": {"level": 10, "max_rank": 3},
            "Tidal Surge": {"level": 10, "max_rank": 2},
            "Ancestral Swiftness": {"level": 10, "max_rank": 1},
            "Undertow": {"level": 10, "max_rank": 2},
            "Improved Chain Heal": {"level": 10, "max_rank": 5},
            "Spirit Link": {"level": 10, "max_rank": 1},
        }
    },
    "Mage": {
        "Arcane": {
            "Arcane Subtlety": {"level": 10, "max_rank": 2},
            "Magic Absorption": {"level": 10, "max_rank": 3},
            "Improved Arcane Missiles": {"level": 10, "max_rank": 5},
            "Wand Specialization": {"level": 10, "max_rank": 2},
            "Arcane Focus": {"level": 10, "max_rank": 5},
            "Arcane Concentration": {"level": 10, "max_rank": 5},
            "Magic Attunement": {"level": 10, "max_rank": 1},
            "Arcane Impact": {"level": 10, "max_rank": 3},
            "Arcane Rupture": {"level": 10, "max_rank": 1},
            "Improved Mana Shield": {"level": 10, "max_rank": 2},
            "Improved Counterspell": {"level": 10, "max_rank": 2},
            "Temporal Convergence": {"level": 10, "max_rank": 3},
            "Arcane Meditation": {"level": 10, "max_rank": 3},
            "Arcane Instability": {"level": 10, "max_rank": 3},
            "Presence of Mind": {"level": 10, "max_rank": 1},
            "Accelerated Arcana": {"level": 10, "max_rank": 1},
            "Arcane Potency": {"level": 10, "max_rank": 2},
            "Resonance Cascade": {"level": 10, "max_rank": 5},
            "Arcane Power": {"level": 10, "max_rank": 1},
        },
        "Fire": {
            "Improved Fireball": {"level": 10, "max_rank": 5},
            "Impact": {"level": 10, "max_rank": 5},
            "Ignite": {"level": 10, "max_rank": 5},
            "Flame Throwing": {"level": 10, "max_rank": 2},
            "Improved Fire Blast": {"level": 10, "max_rank": 3},
            "Incinerate": {"level": 10, "max_rank": 2},
            "Improved Flamestrike": {"level": 10, "max_rank": 3},
            "Pyroblast": {"level": 10, "max_rank": 1},
            "Burning Soul": {"level": 10, "max_rank": 2},
            "Fire Vulnerability": {"level": 10, "max_rank": 3},
            "Improved Fire Ward": {"level": 10, "max_rank": 2},
            "Master of Elements": {"level": 10, "max_rank": 3},
            "Blast Wave": {"level": 10, "max_rank": 1},
            "Critical Mass": {"level": 10, "max_rank": 3},
            "Hot Streak": {"level": 10, "max_rank": 2},
            "Fire Power": {"level": 10, "max_rank": 5},
            "Combustion": {"level": 10, "max_rank": 1},
        },
        "Frost": {
            "Frost Warding": {"level": 10, "max_rank": 2},
            "Improved Frostbolt": {"level": 10, "max_rank": 5},
            "Elemental Precision": {"level": 10, "max_rank": 3},
            "Piercing Ice": {"level": 10, "max_rank": 3},
            "Frostbite": {"level": 10, "max_rank": 3},
            "Improved Frost Nova": {"level": 10, "max_rank": 2},
            "Permafrost": {"level": 10, "max_rank": 3},
            "Ice Shards": {"level": 10, "max_rank": 5},
            "Cold Snap": {"level": 10, "max_rank": 1},
            "Improved Blizzard": {"level": 10, "max_rank": 3},
            "Arctic Reach": {"level": 10, "max_rank": 2},
            "Frost Channeling": {"level": 10, "max_rank": 3},
            "Shatter": {"level": 10, "max_rank": 5},
            "Ice Block": {"level": 10, "max_rank": 1},
            "Icicles": {"level": 10, "max_rank": 1},
            "Improved Cone of Cold": {"level": 10, "max_rank": 3},
            "Winter's Chill": {"level": 10, "max_rank": 5},
            "Flash Freeze": {"level": 10, "max_rank": 2},
            "Ice Barrier": {"level": 10, "max_rank": 1},
        }
    },
    "Warlock": {
        "Affliction": {
            "Suppression": {"level": 10, "max_rank": 5},
            "Improved Corruption": {"level": 10, "max_rank": 5},
            "Sinister Pursuit": {"level": 10, "max_rank": 3},
            "Improved Curse of Weakness": {"level": 10, "max_rank": 2},
            "Resilient Shadows": {"level": 10, "max_rank": 3},
            "Improved Life Tap": {"level": 10, "max_rank": 2},
            "Improved Drains": {"level": 10, "max_rank": 2},
            "Improved Curse of Agony": {"level": 10, "max_rank": 3},
            "Fel Concentration": {"level": 10, "max_rank": 2},
            "Curse of Exhaustion": {"level": 10, "max_rank": 1},
            "Grim Reach": {"level": 10, "max_rank": 2},
            "Nightfall": {"level": 10, "max_rank": 2},
            "Soul Siphon": {"level": 10, "max_rank": 3},
            "Rapid Deterioration": {"level": 10, "max_rank": 2},
            "Siphon Life": {"level": 10, "max_rank": 1},
            "Improved Curse of Exhaustion": {"level": 10, "max_rank": 2},
            "Malediction": {"level": 10, "max_rank": 1},
            "Shadow Mastery": {"level": 10, "max_rank": 5},
            "Dark Harvest": {"level": 10, "max_rank": 1},
        },
        "Demonology": {
            "Master Conjuror": {"level": 10, "max_rank": 2},
            "Demonic Embrace": {"level": 10, "max_rank": 5},
            "Soul Entrapment": {"level": 10, "max_rank": 3},
            "Soul Funnel": {"level": 10, "max_rank": 2},
            "Demonic Aegis": {"level": 10, "max_rank": 3},
            "Fel Intellect": {"level": 10, "max_rank": 3},
            "Fel Domination": {"level": 10, "max_rank": 1},
            "Fel Stamina": {"level": 10, "max_rank": 5},
            "Demonic Sacrifice": {"level": 10, "max_rank": 1},
            "Improved Stones": {"level": 10, "max_rank": 2},
            "Master Summoner": {"level": 10, "max_rank": 2},
            "Nether Studies": {"level": 10, "max_rank": 3},
            "Unholy Power": {"level": 10, "max_rank": 3},
            "Power Overwhelming": {"level": 10, "max_rank": 1},
            "Demonic Precision": {"level": 10, "max_rank": 3},
            "Master Demonologist": {"level": 10, "max_rank": 5},
            "Unleashed Potential": {"level": 10, "max_rank": 3},
            "Soul Link": {"level": 10, "max_rank": 1},
        },
        "Destruction": {
            "Shadow Vulnerability": {"level": 10, "max_rank": 5},
            "Cataclysm": {"level": 10, "max_rank": 5},
            "Demonic Swiftness": {"level": 10, "max_rank": 2},
            "Bane": {"level": 10, "max_rank": 5},
            "Aftermath": {"level": 10, "max_rank": 3},
            "Intensity": {"level": 10, "max_rank": 2},
            "Shadowburn": {"level": 10, "max_rank": 1},
            "Devastation": {"level": 10, "max_rank": 5},
            "Pyroclasm": {"level": 10, "max_rank": 2},
            "Destructive Reach": {"level": 10, "max_rank": 2},
            "Improved Searing Pain": {"level": 10, "max_rank": 5},
            "Improved Soul Fire": {"level": 10, "max_rank": 2},
            "Improved Immolate": {"level": 10, "max_rank": 5},
            "Ruin": {"level": 10, "max_rank": 1},
            "Emberstorm": {"level": 10, "max_rank": 5},
            "Conflagrate": {"level": 10, "max_rank": 1},
        }
    },
    "Druid": {
        "Balance": {
            "Improved Wrath": {"level": 10, "max_rank": 5},
            "Nature's Grasp": {"level": 10, "max_rank": 1},
            "Improved Nature's Grasp": {"level": 10, "max_rank": 4},
            "Sylvan Blessing": {"level": 10, "max_rank": 2},
            "Guidance of the Dream": {"level": 10, "max_rank": 3},
            "Improved Moonfire": {"level": 10, "max_rank": 2},
            "Natural Weapons": {"level": 10, "max_rank": 3},
            "Natural Shapeshifter": {"level": 10, "max_rank": 3},
            "Moonfury": {"level": 10, "max_rank": 3},
            "Omen of Clarity": {"level": 10, "max_rank": 1},
            "Nature's Reach": {"level": 10, "max_rank": 2},
            "Vengeance": {"level": 10, "max_rank": 5},
            "Moonglow": {"level": 10, "max_rank": 3},
            "Owlkin Frenzy": {"level": 10, "max_rank": 3},
            "Moonkin Form": {"level": 10, "max_rank": 1},
            "Nature's Grace": {"level": 10, "max_rank": 1},
            "Improved Starfire": {"level": 10, "max_rank": 3},
            "Balance of All Things": {"level": 10, "max_rank": 5},
            "Gale Winds": {"level": 10, "max_rank": 2},
            "Eclipse": {"level": 10, "max_rank": 1},
        },
        "Feral Combat": {
            "Ferocity": {"level": 10, "max_rank": 5},
            "Feral Aggression": {"level": 10, "max_rank": 5},
            "Feral Instinct": {"level": 10, "max_rank": 3},
            "Brutal Impact": {"level": 10, "max_rank": 2},
            "Thick Hide": {"level": 10, "max_rank": 3},
            "Open Wounds": {"level": 10, "max_rank": 3},
            "Feral Swiftness": {"level": 10, "max_rank": 2},
            "Feral Charge": {"level": 10, "max_rank": 1},
            "Sharpened Claws": {"level": 10, "max_rank": 3},
            "Primal Fury": {"level": 10, "max_rank": 2},
            "Predatory Strikes": {"level": 10, "max_rank": 3},
            "Blood Frenzy": {"level": 10, "max_rank": 2},
            "Improved Shred": {"level": 10, "max_rank": 2},
            "Ancient Brutality": {"level": 10, "max_rank": 2},
            "Berserk": {"level": 10, "max_rank": 1},
            "Heart of the Wild": {"level": 10, "max_rank": 5},
            "Carnage": {"level": 10, "max_rank": 2},
            "Leader of the Pack": {"level": 10, "max_rank": 1},
        },
        "Restoration": {
            "Improved Mark of the Wild": {"level": 10, "max_rank": 5},
            "Furor": {"level": 10, "max_rank": 5},
            "Improved Healing Touch": {"level": 10, "max_rank": 5},
            "Nature's Focus": {"level": 10, "max_rank": 5},
            "Subtlety": {"level": 10, "max_rank": 5},
            "Swiftmend": {"level": 10, "max_rank": 1},
            "Genesis": {"level": 10, "max_rank": 3},
            "Reflection": {"level": 10, "max_rank": 3},
            "Gift of Nature": {"level": 10, "max_rank": 5},
            "Tranquil Spirit": {"level": 10, "max_rank": 5},
            "Aessina's Bloom": {"level": 10, "max_rank": 2},
            "Nature's Swiftness": {"level": 10, "max_rank": 1},
            "Preservation": {"level": 10, "max_rank": 3},
            "Improved Regrowth": {"level": 10, "max_rank": 5},
            "Improved Tranquility": {"level": 10, "max_rank": 2},
            "Tree of Life Form": {"level": 10, "max_rank": 1},
        }
    }
}
