# domain/talent_data.py
# This is a simplified representation of talent data for WoW Classic+.
# The actual talent data would be much more complex and would depend on the specific
# implementation of the Classic+ server.
TALENT_DATA = {
    "Warrior": {
        "Arms": {
            "Improved Heroic Strike": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Tactical Mastery": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Rend": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Charge": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Master Strike": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Overpower": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Deep Wounds": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Two-Handed Weapon Specialization": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Impale": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Master of Arms": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Sweeping Strikes": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Precision Cut": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Disciplines": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Slam": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Mortal Strike": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Boundless Anger": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Booming Voice": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Piercing Howl": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Execute": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
        },
        "Fury": {
            "Cruelty": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Dual Wield Specialization": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Unbridled Wrath": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Shouts": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Blood Craze": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Battlefield Mobility": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Enrage": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Pummel": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Whirlwind": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Death Wish": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Berserker Rage": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Flurry": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Blood Drinker": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Bloodthirst": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Bloodrage": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
        },
        "Protection": {
            "Deflection": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Thunder Clap": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Shield Specialization": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Anticipation": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Iron Will": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Toughness": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Last Stand": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Intervene": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Taunt": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Revenge": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Gag Order": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Disarm": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Defiance": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "One-Handed Weapon Specialization": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Shield Slam": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Shield Slam": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Reprisal": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Shield Wall": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Defensive Tactics": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Concussion Blow": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
        },
    },
    "Paladin": {
        "Holy": {
            "Divine Intellect": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Holy Judgement": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Spiritual Focus": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Seal of Righteousness": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Healing Light": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Sanctity Aura": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Illumination": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Divine Favor": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Holy Shock": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Holy Power": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Blessed Strikes": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Daybreak": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Lay on Hands": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
        },
        "Protection": {
            "Improved Devotion Aura": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Redoubt": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Precision": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Guardian's Favor": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Toughness": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Righteous Fury": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Blessing of Sanctuary": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Shield Specialization": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Anticipation": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Hand of Reckoning": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Hammer of Justice": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Righteous Defense": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Holy Shield": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Reckoning": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Righteous Strikes": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Bulwark of the Righteous": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
        },
        "Retribution": {
            "Improved Blessings": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Benediction": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Judgement": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Seal of the Crusader": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Deflection": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Retribution Aura": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Conviction": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Blessing of Kings": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Pursuit of Justice": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Two-Handed Weapon Specialization": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Vindication": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Eye for an Eye": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Vengeance": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Seal of Command": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Vengeful Strikes": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Repentance": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Divine Strength": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
        },
    },
    "Hunter": {
        "Beast Mastery": {
            "Swift Aspects": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Endurance Training": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Eyes of the Beast": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Primal Aspects": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Thick Hide": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Revive Pet": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Pathfinding": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Coordinated Assault": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Unleashed Fury": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Bestial Discipline": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Mend Pet": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Ferocity": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Intimidation": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Kill Command": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Bestial Precision": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Spirit Bond": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Frenzy": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Baited Shot": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
        },
        "Marksmanship": {
            "Improved Concussive Shot": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Efficiency": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Stings": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Lethal Shots": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Hawk Eye": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Scorpid Sting": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Steady Shot": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Hunter's Mark": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Swiftshot": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Mortal Shots": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Scatter Shot": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Barrage": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Piercing Shots": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Steady Shot": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Endless Quiver": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Ranged Weapon Specialization": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Trueshot Aura": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
        },
        "Survival": {
            "Improved Slaying": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Resourcefulness": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Swift Reflexes": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Entrapment": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Savage Strikes": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Wing Clip": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Planning Ahead": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Survivalist": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Carve": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Deterrence": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Stinging Nettle": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Surefooted": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Feign Death": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Killer Instinct": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Trap Mastery": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Lacerate": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Vicious Strikes": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Lightning Reflexes": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Untamed Trapper": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
        },
    },
    "Rogue": {
        "Assassination": {
            "Improved Eviscerate": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Remorseless Attacks": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Malice": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Ruthlessness": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Murder": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Blade Tactics": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Relentless Strikes": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Throwing Weapon Specialization": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Lethality": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Taste for Blood": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Vile Poisons": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Poisons": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Efficient Poisons": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Envenom": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Cold Blood": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Vigor": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Seal Fate": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Noxious Assault": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
        },
        "Combat": {
            "Opportunity": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Lightning Reflexes": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Deflection": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Backstab": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Precision": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Riposte": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Sprint": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Setup": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Kick": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Concussive Blows": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Dual Wield Specialization": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Close Quarters Combat": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Surprise Attack": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Hack and Slash": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Weapon Expertise": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Blade Rush": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Aggression": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Adrenaline Rush": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
        },
        "Subtlety": {
            "Camouflage": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Expose Armor": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Gouge": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Ambush": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Elusiveness": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Serrated Blades": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Initiative": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Ghostly Strike": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Smoke Bomb": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Hemorrhage": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Cloaked in Shadows": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Blackjack": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Blinding Haze": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Dirty Deeds": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Preparation": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Shadow of Death": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Bloody Mess": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Honor Among Thieves": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Tricks of the Trade": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Mark for Death": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
        },
    },
    "Priest": {
        "Discipline": {
            "Wand Specialization": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Piercing Light": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Mental Agility": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Silent Resolve": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Unbreakable Will": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Blessed Concentration": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Power Word: Fortitude": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Inner Fire": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Inner Focus": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Power Word: Shield": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Meditation": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Searing Light": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Purifying Flames": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Mental Strength": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Enlighten": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Resurgent Shield": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Force of Will": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Chastise": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
        },
        "Holy": {
            "Improved Renew": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Holy Focus": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Divinity": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Divine Fury": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Spell Warding": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Holy Reach": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Blessed Recovery": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Inspiration": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Holy Nova": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Swift Recovery": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Healing": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Spiritual Guidance": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Spirit of Redemption": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Reservoir of Light": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Spiritual Healing": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Proclaim Champion": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
        },
        "Shadow": {
            "Spirit Tap": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Blackout": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Shadow Affinity": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Shadow Word: Pain": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Shadow Focus": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Psychic Scream": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Mind Blast": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Mind Flay": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Mana Burn": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Fade": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Shadow Reach": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Shadow Weaving": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Silence": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Vampiric Embrace": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Vampiric Touch": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Darkness": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Shadowform": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
        },
    },
    "Shaman": {
        "Elemental": {
            "Convection": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Concussion": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Earth's Grasp": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Elemental Warding": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Elemental Devastation": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Elemental Focus": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Reverberation": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Call of Thunder": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Molten Blast": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Fire Totems": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Eye of the Storm": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Call of Flame": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Storm Reach": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Elemental Mastery": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Elemental Fury": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Lightning Mastery": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Earthquake": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
        },
        "Enhancement": {
            "Ancestral Knowledge": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Shield Specialization": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Totemic Alignment": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Thundering Strikes": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Stable Shields": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Ghost Wolf": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Calming Winds": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Lightning Strike": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Ancestral Guardian": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Flurry": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Spirit Armor": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Enhancing Totems": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Elemental Weapons": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Stormstrike": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Element's Grace": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Bloodlust": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
        },
        "Restoration": {
            "Improved Healing Wave": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Tidal Focus": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Reincarnation": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Ancestral Healing": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Tidal Mastery": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Healing Way": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Healing Focus": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Totemic Mastery": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Nature's Grace": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Restorative Totems": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Water Shield": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Tidal Surge": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Ancestral Swiftness": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Undertow": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Chain Heal": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Spirit Link": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
        },
    },
    "Mage": {
        "Arcane": {
            "Arcane Subtlety": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Magic Absorption": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Arcane Missiles": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Wand Specialization": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Arcane Focus": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Arcane Concentration": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Magic Attunement": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Arcane Impact": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Arcane Rupture": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Mana Shield": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Counterspell": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Temporal Convergence": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Arcane Meditation": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Arcane Instability": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Presence of Mind": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Accelerated Arcana": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Arcane Potency": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Resonance Cascade": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Arcane Power": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
        },
        "Fire": {
            "Improved Fireball": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Impact": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Ignite": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Flame Throwing": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Fire Blast": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Incinerate": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Flamestrike": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Pyroblast": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Burning Soul": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Fire Vulnerability": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Fire Ward": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Master of Elements": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Blast Wave": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Critical Mass": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Hot Streak": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Fire Power": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Combustion": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
        },
        "Frost": {
            "Frost Warding": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Frostbolt": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Elemental Precision": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Piercing Ice": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Frostbite": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Frost Nova": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Permafrost": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Ice Shards": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Cold Snap": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Blizzard": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Arctic Reach": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Frost Channeling": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Shatter": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Ice Block": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Icicles": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Cone of Cold": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Winter's Chill": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Flash Freeze": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Ice Barrier": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
        },
    },
    "Warlock": {
        "Affliction": {
            "Suppression": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Corruption": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Sinister Pursuit": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Curse of Weakness": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Resilient Shadows": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Life Tap": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Drains": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Curse of Agony": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Fel Concentration": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Curse of Exhaustion": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Grim Reach": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Nightfall": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Soul Siphon": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Rapid Deterioration": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Siphon Life": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Curse of Exhaustion": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Malediction": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Shadow Mastery": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Dark Harvest": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
        },
        "Demonology": {
            "Master Conjuror": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Demonic Embrace": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Soul Entrapment": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Soul Funnel": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Demonic Aegis": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Fel Intellect": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Fel Domination": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Fel Stamina": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Demonic Sacrifice": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Stones": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Master Summoner": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Nether Studies": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Unholy Power": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Power Overwhelming": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Demonic Precision": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Master Demonologist": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Unleashed Potential": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Soul Link": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
        },
        "Destruction": {
            "Shadow Vulnerability": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Cataclysm": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Demonic Swiftness": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Bane": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Aftermath": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Intensity": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Shadowburn": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Devastation": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Pyroclasm": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Destructive Reach": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Searing Pain": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Soul Fire": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Immolate": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Ruin": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Emberstorm": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Conflagrate": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
        },
    },
    "Druid": {
        "Balance": {
            "Improved Wrath": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Nature's Grasp": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Nature's Grasp": {
                "level": 10,
                "max_rank": 4,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Sylvan Blessing": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Guidance of the Dream": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Moonfire": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Natural Weapons": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Natural Shapeshifter": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Moonfury": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Omen of Clarity": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Nature's Reach": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Vengeance": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Moonglow": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Owlkin Frenzy": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Moonkin Form": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Nature's Grace": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Starfire": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Balance of All Things": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Gale Winds": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Eclipse": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
        },
        "Feral Combat": {
            "Ferocity": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Feral Aggression": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Feral Instinct": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Brutal Impact": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Thick Hide": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Open Wounds": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Feral Swiftness": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Feral Charge": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Sharpened Claws": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Primal Fury": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Predatory Strikes": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Blood Frenzy": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Shred": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Ancient Brutality": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Berserk": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Heart of the Wild": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Carnage": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Leader of the Pack": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
        },
        "Restoration": {
            "Improved Mark of the Wild": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Furor": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Healing Touch": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Nature's Focus": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Subtlety": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Swiftmend": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Genesis": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Reflection": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Gift of Nature": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Tranquil Spirit": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Aessina's Bloom": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Nature's Swiftness": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Preservation": {
                "level": 10,
                "max_rank": 3,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Regrowth": {
                "level": 10,
                "max_rank": 5,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Improved Tranquility": {
                "level": 10,
                "max_rank": 2,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
            "Tree of Life Form": {
                "level": 10,
                "max_rank": 1,
                "tier": 1,
                "requires": [],
                "required_by": [],
            },
        },
    },
}
